var heading = document.getElementById("heading")
var para = document.getElementsByClassName("para")
var tag = document.getElementsByTagName("a")
var query = document.querySelector("#heading")
var query1 = document.querySelector(".para")
console.log(para.length)
console.log(para[0])
console.log(para[1])
console.log(heading)
console.log(tag)
console.log(query)
console.log(query1)

// para.push("deepu")
